//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5420
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftStore {
    
    public partial class home {
        protected System.Web.UI.HtmlControls.HtmlForm form1;
        protected System.Web.UI.ScriptManager ScriptManager1;
        protected SoftStore.controls.master_header Master_header1;
        protected SoftStore.controls.master_top_best_soft Master_top_best_soft1;
        protected SoftStore.controls.master_index_bar Master_index_bar1;
        protected SoftStore.controls.master_left_group Master_left_group1;
        protected System.Web.UI.WebControls.ContentPlaceHolder ContentPlaceHolder1;
        protected SoftStore.controls.master_footer Master_footer1;
    }
}
