//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftStore.admin.controls {
    
    public partial class contact {
        protected System.Web.UI.WebControls.Panel paList;
        protected System.Web.UI.WebControls.Repeater rptList;
        protected SiteUtils.CollectionPager pagerList;
        protected System.Web.UI.WebControls.ImageButton btnDel;
        protected System.Web.UI.WebControls.Panel paEdit;
        protected System.Web.UI.WebControls.Label lblFullName;
        protected System.Web.UI.WebControls.Label lblEmail;
        protected System.Web.UI.WebControls.Label lblCompany;
        protected System.Web.UI.WebControls.Label lblTel;
        protected System.Web.UI.WebControls.Label lblAddress;
        protected System.Web.UI.WebControls.Label lblMobile;
        protected System.Web.UI.WebControls.Label lblEdate;
        protected System.Web.UI.WebControls.Label lblContent;
        protected System.Web.UI.WebControls.ImageButton btnBack;
    }
}
