//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5420
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftStore.admin.controls {
    
    public partial class orderslist {
        protected System.Web.UI.WebControls.Panel paList;
        protected System.Web.UI.WebControls.Repeater rptList;
        protected System.Web.UI.WebControls.ImageButton btnDel;
        protected System.Web.UI.WebControls.Panel paEdit;
        protected System.Web.UI.WebControls.Label lblName;
        protected System.Web.UI.WebControls.Label lblAddress;
        protected System.Web.UI.WebControls.Label lblPhone;
        protected System.Web.UI.WebControls.Label lblEmail;
        protected System.Web.UI.WebControls.Label lblReceiveAddress;
        protected System.Web.UI.WebControls.Label lblReceiveMethods;
        protected System.Web.UI.WebControls.Label lblPaymentMethods;
        protected System.Web.UI.WebControls.Label lblDes;
        protected System.Web.UI.WebControls.Repeater rptBasket;
        protected System.Web.UI.WebControls.Label lblTotal;
        protected System.Web.UI.WebControls.ImageButton btnBack;
    }
}
