//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5420
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftStore.admin.controls {
    
    public partial class products {
        protected System.Web.UI.WebControls.Panel paList;
        protected System.Web.UI.WebControls.Repeater rptList;
        protected SiteUtils.CollectionPager pagerList;
        protected System.Web.UI.WebControls.ImageButton btnNew;
        protected System.Web.UI.WebControls.ImageButton btnDel;
        protected System.Web.UI.WebControls.ImageButton btnSetHot;
        protected System.Web.UI.WebControls.ImageButton btnPublished;
        protected System.Web.UI.WebControls.Panel paEdit;
        protected System.Web.UI.WebControls.DropDownList drlCategory;
        protected System.Web.UI.WebControls.TextBox txtProductID;
        protected System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator2;
        protected System.Web.UI.WebControls.TextBox txtProductName;
        protected System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator1;
        protected System.Web.UI.WebControls.DropDownList drlSupplierID;
        protected System.Web.UI.WebControls.TextBox txtVersion;
        protected System.Web.UI.WebControls.TextBox txtPrice;
        protected System.Web.UI.WebControls.TextBox txtPromotionRate;
        protected System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator3;
        protected System.Web.UI.WebControls.RangeValidator RangeValidator1;
        protected System.Web.UI.WebControls.RadioButton rdbStatusYes;
        protected System.Web.UI.WebControls.RadioButton rdbStatusNo;
        protected System.Web.UI.WebControls.CheckBox cbkIsBest;
        protected System.Web.UI.WebControls.CheckBox cbkIsBestSale;
        protected System.Web.UI.WebControls.CheckBox cbkKM;
        protected System.Web.UI.WebControls.CheckBoxList drlProdcuctPack;
        protected System.Web.UI.HtmlControls.HtmlInputText txtReleaseDate;
        protected System.Web.UI.HtmlControls.HtmlInputText txtUpdateDate;
        protected System.Web.UI.WebControls.TextBox txtLinkDownload;
        protected System.Web.UI.HtmlControls.HtmlInputFile imgAdv;
        protected System.Web.UI.HtmlControls.HtmlImage imgpic;
        protected System.Web.UI.WebControls.Label lblPic;
        protected System.Web.UI.WebControls.RadioButton rdbPublishY;
        protected System.Web.UI.WebControls.RadioButton rdbIsPublishN;
        protected System.Web.UI.WebControls.TextBox txtTags;
        protected System.Web.UI.WebControls.TextBox txtKeywordsContent;
        protected CKEditor.NET.CKEditorControl txtDetailDescription;
        protected CKEditor.NET.CKEditorControl txtTechDescription;
        protected System.Web.UI.WebControls.ImageButton btnSubmit;
        protected System.Web.UI.WebControls.ImageButton btnCancel;
    }
}
