//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5420
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftStore.controls {
    
    public partial class news {
        protected System.Web.UI.WebControls.Label lblTitle;
        protected System.Web.UI.WebControls.Panel paList;
        protected System.Web.UI.WebControls.Repeater rptListNews;
        protected System.Web.UI.WebControls.Panel paDetail;
        protected System.Web.UI.WebControls.Repeater rptDetail;
    }
}
