//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5420
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftStore.controls {
    
    public partial class paymentcart {
        protected System.Web.UI.WebControls.Literal ltCartNull;
        protected System.Web.UI.WebControls.Panel paStep1;
        protected System.Web.UI.WebControls.TextBox txtCustomerName;
        protected System.Web.UI.WebControls.TextBox txtAddress;
        protected System.Web.UI.WebControls.TextBox txtPhone;
        protected System.Web.UI.WebControls.TextBox txtEmail;
        protected System.Web.UI.WebControls.TextBox txtReceiveAddress;
        protected System.Web.UI.WebControls.TextBox txtDescription;
        protected System.Web.UI.WebControls.Button btnContinue;
        protected System.Web.UI.WebControls.Button btnEditCart;
        protected System.Web.UI.WebControls.Panel paStep2;
        protected System.Web.UI.WebControls.Repeater rptReceiveMethod;
        protected System.Web.UI.WebControls.Button btnBackToStep1;
        protected System.Web.UI.WebControls.Button btnStep2Continue;
        protected System.Web.UI.WebControls.Panel paStep3;
        protected System.Web.UI.WebControls.Repeater rptPaymentMethod;
        protected System.Web.UI.WebControls.Button btnBacktoStep2;
        protected System.Web.UI.WebControls.Button btnStep3Continue;
        protected System.Web.UI.WebControls.Panel paStep4;
        protected System.Web.UI.WebControls.Label lblCustomerName;
        protected System.Web.UI.WebControls.Label lblAddress;
        protected System.Web.UI.WebControls.Label lblPhone;
        protected System.Web.UI.WebControls.Label lblEmail;
        protected System.Web.UI.WebControls.Label lblReceiveAddress;
        protected System.Web.UI.WebControls.Label lblDescription;
        protected System.Web.UI.WebControls.Label lblReceiveMethod;
        protected System.Web.UI.WebControls.Label lblPaymentMethod;
        protected System.Web.UI.WebControls.Repeater rptBasket;
        protected System.Web.UI.WebControls.Label lblTotal;
        protected System.Web.UI.WebControls.Button btnBackToStep3;
        protected System.Web.UI.WebControls.Button btnFinish;
    }
}
