//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5420
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftStore.controls {
    
    public partial class product_detail {
        protected System.Web.UI.WebControls.Literal ltProductName;
        protected System.Web.UI.WebControls.Literal ltPic;
        protected System.Web.UI.WebControls.Literal ltPrice;
        protected System.Web.UI.WebControls.Literal ltSaleOff;
        protected System.Web.UI.WebControls.DropDownList drlPackages;
        protected AjaxControlToolkit.Rating Rating1;
        protected System.Web.UI.WebControls.Literal ltLinkDownload;
        protected System.Web.UI.WebControls.Literal ltCountComments;
        protected System.Web.UI.WebControls.Literal ltDetailDes;
        protected System.Web.UI.WebControls.Literal ltTechDes;
        protected SoftStore.controls.productcomments Productcomments1;
        protected System.Web.UI.WebControls.Literal ltTags;
    }
}
