//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5420
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftStore.controls {
    
    public partial class request {
        protected System.Web.UI.WebControls.TextBox txtFullName;
        protected System.Web.UI.WebControls.TextBox txtCompany;
        protected System.Web.UI.WebControls.TextBox txtPhone;
        protected System.Web.UI.WebControls.TextBox txtEmail;
        protected System.Web.UI.WebControls.TextBox txtSoft;
        protected System.Web.UI.WebControls.TextBox txtCN;
        protected WebControlCaptcha.CaptchaControl captchaCode;
        protected System.Web.UI.WebControls.Button btnRegister;
    }
}
