//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5420
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftStore.admin {
    
    public partial class admin {
        protected System.Web.UI.HtmlControls.HtmlForm form1;
        protected System.Web.UI.WebControls.Literal ltName;
        protected SoftStore.admin.controls.menu Menu1;
        protected System.Web.UI.WebControls.ContentPlaceHolder ContentPlaceHolder1;
    }
}
