//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5420
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftStore.admin.controls {
    
    public partial class help {
        protected System.Web.UI.WebControls.Panel paEdit;
        protected System.Web.UI.WebControls.TextBox txtTitle;
        protected System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator1;
        protected System.Web.UI.WebControls.RadioButton rdbYes;
        protected System.Web.UI.WebControls.RadioButton rdbNo;
        protected CKEditor.NET.CKEditorControl txtContent;
        protected System.Web.UI.WebControls.ImageButton btnSubmit;
        protected System.Web.UI.WebControls.ImageButton btnCancel;
    }
}
