//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5420
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftStore.admin.controls {
    
    public partial class brands {
        protected System.Web.UI.WebControls.Panel paList;
        protected System.Web.UI.WebControls.Repeater rptList;
        protected System.Web.UI.WebControls.ImageButton btnNew;
        protected System.Web.UI.WebControls.ImageButton btnDel;
        protected System.Web.UI.WebControls.Panel paEdit;
        protected System.Web.UI.WebControls.TextBox txtName;
        protected System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator1;
        protected System.Web.UI.WebControls.TextBox txtUrl;
        protected System.Web.UI.WebControls.TextBox txtIndex;
        protected System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator2;
        protected System.Web.UI.WebControls.RangeValidator RangeValidator1;
        protected System.Web.UI.WebControls.TextBox txtDescription;
        protected System.Web.UI.HtmlControls.HtmlInputFile imgAdv;
        protected System.Web.UI.WebControls.Label lblPic;
        protected System.Web.UI.WebControls.Literal ltImgFlash;
        protected System.Web.UI.HtmlControls.HtmlImage imgpic;
        protected System.Web.UI.WebControls.ImageButton btnSubmit;
        protected System.Web.UI.WebControls.ImageButton btnCancel;
    }
}
