//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5420
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftStore.admin.controls {
    
    public partial class news {
        protected System.Web.UI.WebControls.Panel paList;
        protected System.Web.UI.WebControls.DropDownList drlCategory;
        protected System.Web.UI.WebControls.Repeater rptList;
        protected SiteUtils.CollectionPager pagerList;
        protected System.Web.UI.WebControls.ImageButton btnNew;
        protected System.Web.UI.WebControls.ImageButton btnDel;
        protected System.Web.UI.WebControls.ImageButton btnPublished;
        protected System.Web.UI.WebControls.Panel paEdit;
        protected System.Web.UI.WebControls.DropDownList drlCategoryNew;
        protected System.Web.UI.WebControls.TextBox txtTitle;
        protected System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator1;
        protected System.Web.UI.HtmlControls.HtmlInputFile imgAdv;
        protected System.Web.UI.HtmlControls.HtmlImage imgpic;
        protected System.Web.UI.WebControls.CheckBox cbkDelImg;
        protected System.Web.UI.WebControls.Label lblPic;
        protected System.Web.UI.WebControls.TextBox txtPicNote;
        protected System.Web.UI.WebControls.CheckBox cbkIsHot;
        protected System.Web.UI.WebControls.RadioButton rdbPublishY;
        protected System.Web.UI.WebControls.RadioButton rdbIsPublishN;
        protected CKEditor.NET.CKEditorControl txtIntro;
        protected CKEditor.NET.CKEditorControl txtContent;
        protected System.Web.UI.WebControls.ImageButton btnSubmit;
        protected System.Web.UI.WebControls.ImageButton btnCancel;
    }
}
