//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5420
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftStore.controls {
    
    public partial class edit_profile {
        protected System.Web.UI.WebControls.Label txtUserName;
        protected System.Web.UI.HtmlControls.HtmlImage imgAvatar;
        protected System.Web.UI.WebControls.TextBox txtFullName;
        protected System.Web.UI.WebControls.TextBox txtAddress;
        protected System.Web.UI.WebControls.TextBox txtPhone;
        protected System.Web.UI.WebControls.TextBox txtMobile;
        protected System.Web.UI.WebControls.TextBox txtEmail;
        protected System.Web.UI.HtmlControls.HtmlInputFile flAvatar;
        protected WebControlCaptcha.CaptchaControl captchaCode;
        protected System.Web.UI.WebControls.Label lblAvatar;
        protected System.Web.UI.WebControls.Button btnRegister;
    }
}
