//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5420
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftStore.controls {
    
    public partial class shoppingcart {
        protected System.Web.UI.WebControls.Repeater rptBasket;
        protected System.Web.UI.WebControls.Label lblTotal;
        protected System.Web.UI.WebControls.Button btnUpdate;
        protected System.Web.UI.WebControls.Button btnContinue;
        protected System.Web.UI.WebControls.Button btnPayment;
    }
}
