//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5420
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftStore.controls {
    
    public partial class contact {
        protected System.Web.UI.WebControls.Literal ltCompany;
        protected System.Web.UI.WebControls.Literal ltAddress;
        protected System.Web.UI.WebControls.Literal ltPhone;
        protected System.Web.UI.WebControls.Literal ltFax;
        protected System.Web.UI.WebControls.Literal ltHotMail;
        protected System.Web.UI.WebControls.Literal ltEmail;
        protected System.Web.UI.WebControls.Literal ltWebsite;
        protected System.Web.UI.WebControls.TextBox txtFullName;
        protected System.Web.UI.WebControls.TextBox txtAddress;
        protected System.Web.UI.WebControls.TextBox txtPhone;
        protected System.Web.UI.WebControls.TextBox txtFax;
        protected System.Web.UI.WebControls.TextBox txtEmail;
        protected System.Web.UI.WebControls.TextBox txtContent;
        protected System.Web.UI.WebControls.Button btnSend;
    }
}
