//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5420
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftStore.controls {
    
    public partial class master_header {
        protected System.Web.UI.WebControls.Literal ltLoginPanel;
        protected System.Web.UI.WebControls.TextBox txtKey;
        protected System.Web.UI.WebControls.Literal ltCart;
        protected System.Web.UI.WebControls.Literal ltMenu;
    }
}
