//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5420
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftStore.controls {
    
    public partial class master_left_group {
        protected System.Web.UI.WebControls.Literal ltMenuLeft;
        protected SoftStore.controls.master_supportonline Master_supportonline1;
        protected SoftStore.controls.onl_statistics Onl_statistics1;
    }
}
