//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5420
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftStore.admin.controls {
    
    public partial class members {
        protected System.Web.UI.WebControls.Panel paList;
        protected System.Web.UI.WebControls.Repeater rptList;
        protected System.Web.UI.WebControls.ImageButton btnNew;
        protected System.Web.UI.WebControls.ImageButton btnDel;
        protected System.Web.UI.WebControls.Panel paEdit;
        protected System.Web.UI.WebControls.TextBox txtFullName;
        protected System.Web.UI.HtmlControls.HtmlImage imgAvatar;
        protected System.Web.UI.WebControls.TextBox txtUserName;
        protected System.Web.UI.HtmlControls.HtmlTableRow rowPass;
        protected System.Web.UI.WebControls.TextBox txtPassword;
        protected System.Web.UI.HtmlControls.HtmlTableRow rowReset;
        protected System.Web.UI.WebControls.TextBox txtAddress;
        protected System.Web.UI.WebControls.TextBox txtPhone;
        protected System.Web.UI.WebControls.TextBox txtMobile;
        protected System.Web.UI.WebControls.TextBox txtEmail;
        protected System.Web.UI.WebControls.RadioButton rdbActivateY;
        protected System.Web.UI.WebControls.RadioButton rdbActivateN;
        protected System.Web.UI.WebControls.Label lblAvatar;
        protected System.Web.UI.HtmlControls.HtmlInputFile flAvatar;
        protected System.Web.UI.WebControls.ImageButton btnSubmit;
        protected System.Web.UI.WebControls.ImageButton btnCancel;
    }
}
